# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
