# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Mars', max_length=30),
        ),
    ]
